-- 코드를 입력하세요
SELECT B.CATEGORY, SUM(BS.SALES) as TOTAL_SALES
FROM BOOK as B, BOOK_SALES as BS
WHERE YEAR(BS.SALES_DATE)=2022 AND MONTH(BS.SALES_DATE)=1 AND B.BOOK_ID=BS.BOOK_ID
GROUP BY B.CATEGORY
ORDER BY B.CATEGORY
